FROM centos:6.8

COPY ./build_and_install_deps.sh ./recipe_wrapper.sh ./Makefile ./build_container_common.sh /
COPY WORKSPACE /bazel-prebuilt/
COPY ./api /bazel-prebuilt/api
COPY ./bazel /bazel-prebuilt/bazel
COPY ./build_recipes/*.sh /build_recipes/

COPY ./build_container_centos6.sh /

RUN ./build_container_centos6.sh
